name: Build Docs

on:
  push:
    branches:
      main

jobs:
  buildDocs:
    name: Build Docs üñ•Ô∏è
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          working-directory: "Docs"
          doxyfile-path: "Doxyfile" 
      - uses: actions/upload-artifact@v2
        with:
          name: FlowEnt.Docs
          path: Docs/html


  deployPages:
    needs: buildDocs
    name: Deploy Docs To Page üöÄ
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: FlowEnt.Docs
          path: Docs/html

      - name: Display structure of root files
        run: ls -R
        working-directory: Docs/html

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: docs/main
          folder: Docs/html